application: woodchathk
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /img
  static_dir: static/img

- url: /css
  static_dir: static/css
  
- url: /js
  static_dir: static/js

- url: /html
  static_dir: static/html
  
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: .*
  script: wsgi.application

libraries:
- name: django
  version: "1.5"

builtins:
- django_wsgi: on
